"""String error code constants used by ChironError subclasses and HTTP responses."""

# Generic
ERROR = "ERROR"
CHIRON_ERROR = "CHIRON_ERROR"

# RAG / retrieval pipeline
RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
EMBEDDING_ERROR = "EMBEDDING_ERROR"
RERANK_ERROR = "RERANK_ERROR"
PIPELINE_ERROR = "PIPELINE_ERROR"

# Ingestion / crawling
INDEXING_ERROR = "INDEXING_ERROR"
INGESTION_ERROR = "INGESTION_ERROR"
CRAWL_ERROR = "CRAWL_ERROR"

# Auth / proxy
AUTH_ERROR = "AUTH_ERROR"
PROXY_ERROR = "PROXY_ERROR"

# Validation
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND_ERROR = "NOT_FOUND_ERROR"
