[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True

[mypy-infrastructure.*]
ignore_errors = True

[mypy-api.*]
ignore_errors = True

[mypy-application.*]
ignore_errors = True

[mypy-core.contracts.*]
ignore_errors = False

[mypy-domain.*]
ignore_errors = False
