export const MD_STEP_TYPES_META = [
  {
    type: "strip_meta_block",
    title: "Strip meta block",
    description:
      "Removes the leading HTML comment <!-- meta ... --> at the start of the document, parses fields (url, framework, doc_kind, etc.) and returns them as meta; only the remaining text (body) continues through the pipeline.",
    example:
      'Input: "<!--\\nmeta: ...\\n-->\\n\\n# Title\\nContent" → meta = {...}, body = "# Title\\nContent". If no comment — meta = {}, body = original text.',
  },
  {
    type: "delete_lines_exact",
    title: "Delete lines (exact match)",
    description:
      'Removes lines that exactly match one of the given strings after strip (e.g. UI boilerplate: "View in English", "Table of Contents").',
    example:
      'Param lines: ["View in English", "Contents"]. Lines equal to these after trimming are dropped; others stay.',
  },
  {
    type: "delete_lines_containing",
    title: "Delete lines containing",
    description:
      'Removes lines that contain any of the given substrings (useful for link lines like "[View in English](url)").',
    example:
      'Param substrings: ["view in english", "view in russian"]. Line "[View in English](https://...)" is removed; main content lines stay.',
  },
  {
    type: "delete_lines_regex",
    title: "Delete lines (regex)",
    description:
      "Removes each line that matches the given regex as a whole (line-by-line check).",
    example:
      'Param pattern: "^\\s*\\[.*[Vv]iew in [Ee]nglish\\].*$" removes all "View in English" link lines. Other lines are kept.',
  },
  {
    type: "delete_sentences_starting_with",
    title: "Delete sentences starting with",
    description:
      "Removes whole prose sentences whose trimmed text starts with one of the configured prefixes, ignoring upper/lower case. Fenced code blocks are preserved.",
    example:
      'Param prefixes: ["Today we are", "In this article"]. Sentences starting with those words are removed; other sentences remain.',
  },
  {
    type: "delete_range_regex",
    title: "Delete range (regex)",
    description:
      "Finds a range in the text: from the first match of start_regex to the first match of end_regex after it (or to end of document if end_regex is omitted). That range is cut out and removed.",
    example:
      'Params start_regex: "^## Conforming Types", end_regex: "^## ". The block from that heading to the next ## is removed (e.g. autogenerated sections).',
  },
  {
    type: "delete_regex_match",
    title: "Extract and delete regex match",
    description:
      "Finds all non-overlapping matches of one regex (including multiline) and removes each match. Useful for cutting blocks by a single pattern (e.g. from marker to marker).",
    example:
      'Param pattern: "(?ms)^<!-- no-index -->.*?^<!-- /no-index -->" — removes all blocks between those comments. Or a pattern for "[View in English](...)" link lines only.',
  },
  {
    type: "strip_sections_by_heading",
    title: "Strip sections by heading",
    description:
      "Removes entire markdown sections by heading: if the heading (normalized: no #, lower) equals or starts with one of the list, the section from that heading to the next same-or-higher-level heading is removed.",
    example:
      'Param headings: ["conforming types", "inherited by", "inherits from"]. Section "## Conforming Types\\n...\\n### Details" up to "## Next Section" is removed.',
  },
  {
    type: "normalize_whitespace",
    title: "Normalize whitespace",
    description:
      "Trims trailing space per line, strips leading/trailing blank lines, collapses two or more spaces to one. Does not change content inside fenced code blocks (```) or lines with 4+ leading spaces.",
    example:
      'Input: "  Title  \\n\\n  line   with   spaces  \\n" → "Title\\n\\nline with spaces".',
  },
  {
    type: "wrap_indented_code",
    title: "Wrap indented code blocks",
    description:
      "Finds non-fenced 4-space-indented code blocks outside ``` and wraps them into fenced code blocks (optionally with a language, e.g. ```swift).",
    example:
      "Swift docs snippet with indented code (4 spaces at start of each line) becomes a fenced ```swift block.",
  },
  {
    type: "replace_regex",
    title: "Replace regex",
    description:
      "Replaces every match of the regex with the given string (e.g. to clean up stray characters or tags).",
    example:
      'Param pattern: "\\s{3,}", replacement: "\\n\\n" — three or more spaces/newlines become two newlines.',
  },
  {
    type: "reject_low_signal_body",
    title: "Reject low-signal body",
    description:
      "After cleanup, drops the entire body (outputs empty markdown) if the text is too weak for RAG: fewer than min_chars characters, fewer than min_words words, or alphabetic letters below min_alpha_ratio of non-space characters (filters link/nav soup). Short but dense prose can still pass.",
    example:
      "Params: min_chars 200, min_words 5, min_alpha_ratio 0.12 — place this step at the end of the pipeline (and tune thresholds in JSON).",
  },
];

export const SECTION_TABS = [
  { id: "crawler", label: "Crawler" },
  { id: "md-pipeline", label: "MD Pipeline" },
];
export const CREATE_COLLECTION_LIVE_ID = "crawler-create-collection";
export const CREATE_COLLECTION_POLL_INTERVAL_MS = 333;
