/* eslint-disable */
// This file is generated by CoreModules/CoreUI/scripts/gen_api_types.mjs.
// Source of truth: backend OpenAPI from core.openapi.build_openapi_spec(create_app()).

interface components {
  schemas: {
    AppSettingsResponse: {
      developer_mode?: boolean;
      rag_collection?: string;
      server_port?: number;
      server_port_active?: number;
      server_port_restart_required?: boolean;
      server_port_source?: string;
      status?: string;
      [key: string]: unknown;
    };
    DependenciesResponse: {
      counts?: Record<string, number>;
      dependencies?: components["schemas"]["Dependency"][];
      files?: string[];
      generated_at?: string;
      update_capabilities?: Record<string, unknown>[];
    };
    Dependency: {
      ecosystem?: string;
      id?: string;
      installed_version?: string | null;
      latest_version?: string | null;
      manager?: string;
      name?: string;
      requested?: string;
      sources?: components["schemas"]["DependencySource"][];
      status?: string;
    };
    DependencyJobResponse: {
      job?: Record<string, unknown>;
    };
    DependencySource: {
      group?: string;
      path?: string;
      requested?: string;
    };
    DockerListResponse: {
      containers?: Record<string, unknown>[];
      details?: string;
      error?: string;
      images?: Record<string, unknown>[];
      items?: Record<string, unknown>[];
      ok?: boolean;
      [key: string]: unknown;
    };
    DockerStatusResponse: {
      available?: boolean;
      details?: string;
      error?: string;
      ok?: boolean;
      running?: boolean;
      version?: string;
      [key: string]: unknown;
    };
    ErrorResponse: {
      error?: string | Record<string, unknown>;
      [key: string]: unknown;
    };
    ExtensionCapability: {
      description?: string;
      id?: string;
      label?: string;
      requires_user_consent?: boolean;
      risk?: string;
      [key: string]: unknown;
    };
    ExtensionCard: {
      blocklist?: Record<string, unknown>;
      capabilities?: components["schemas"]["ExtensionCapability"][];
      description?: string;
      icon?: string;
      id?: string;
      latest_version?: string;
      publisher?: Record<string, unknown>;
      repository?: string;
      repository_id?: string;
      title?: string;
      visibility?: string;
      [key: string]: unknown;
    };
    ExtensionDockerStatus: {
      container_name?: string;
      current_version?: string;
      data_persisted?: boolean;
      image?: string;
      running?: boolean;
      update_available?: boolean;
      update_status?: string;
      update_version?: string;
      [key: string]: unknown;
    };
    ExtensionRegistryResponse: {
      cache_age_sec?: number;
      entries?: components["schemas"]["ExtensionCard"][];
      registry_url?: string;
      [key: string]: unknown;
    };
    ExtensionTab: {
      description?: string;
      extension_id?: string;
      frame?: Record<string, unknown>;
      icon?: string;
      icon_url?: string;
      id?: string;
      load_state?: components["schemas"]["ExtensionTabLoadState"];
      order?: number;
      status?: Record<string, unknown> | null;
      title?: string;
      [key: string]: unknown;
    };
    ExtensionTabLoadState: {
      cached_at?: string;
      duration_ms?: number | null;
      error?: string;
      finished_at?: string;
      job_id?: string;
      phases?: Record<string, string>;
      started_at?: string;
      status?: string;
    };
    ExtensionTabsResponse: {
      available?: boolean;
      runtime_status?: string;
      tabs?: components["schemas"]["ExtensionTab"][];
    };
    GenericObject: Record<string, unknown>;
    InstalledExtension: {
      docker?: components["schemas"]["ExtensionDockerStatus"];
      enabled?: boolean;
      error?: string;
      id?: string;
      installed?: boolean;
      restart_required?: boolean;
      sandbox_status?: string;
      sandboxed?: boolean;
      security_blocked?: boolean;
      status?: string;
      version?: string;
      [key: string]: unknown;
    };
    InstalledExtensionsResponse: {
      extensions?: components["schemas"]["InstalledExtension"][];
      [key: string]: unknown;
    };
    LlmProxyBuildRow: {
      backend?: string;
      healthy?: boolean;
      id?: string;
      issues?: string[];
      label?: string;
      model?: string;
      prompt_name?: string;
      use_prompt_template?: boolean;
      [key: string]: unknown;
    };
    LlmProxyBuildsGetResponse: {
      builds?: components["schemas"]["LlmProxyBuildRow"][];
      openai_models_urls?: {
        main?: string;
      };
    };
    LlmProxyBuildsPutOkResponse: {
      builds?: components["schemas"]["LlmProxyBuildRow"][];
      ok?: boolean;
    };
    LlmProxyStatusResponse: {
      base_url?: string;
      enabled?: boolean;
      health?: string;
    };
    ModelSettingsGetResponse: Record<string, unknown>;
    ModelSettingsPostResponse: {
      settings?: Record<string, unknown>;
      status?: string;
    };
    ModelsListResponse: {
      models: components["schemas"]["ProviderModelEntry"][];
    };
    OpenAiChatCompletionRequest: {
      messages: Record<string, unknown>[];
      model?: string;
      stream?: boolean;
      temperature?: number;
      tool_choice?: string | Record<string, unknown>;
      tools?: Record<string, unknown>[];
      [key: string]: unknown;
    };
    OpenAiChatCompletionResponse: Record<string, unknown>;
    OpenAiModelListResponse: {
      data?: components["schemas"]["OpenAiModelResponse"][];
      object?: string;
    };
    OpenAiModelResponse: {
      created?: number;
      id?: string;
      metadata?: Record<string, unknown>;
      modalities?: string[];
      object?: string;
      owned_by?: string;
      supports_tools?: boolean;
      supports_vision?: boolean;
      [key: string]: unknown;
    };
    ProviderModelEntry: {
      description?: string;
      id?: string;
      modified_at?: string;
      name?: string;
      size?: number;
      [key: string]: unknown;
    };
    RagCollectionsResponse: {
      active_collection?: string;
      collections?: Record<string, unknown>[];
      error?: string;
      [key: string]: unknown;
    };
    RagStatusResponse: {
      collections?: string[];
      error?: string;
      qdrant?: Record<string, unknown>;
      status?: string;
      [key: string]: unknown;
    };
    StartupPerformanceResponse: {
      browser_timing?: Record<string, unknown>;
      phases?: Record<string, unknown>[];
      server_start_epoch_ms?: number;
      total_duration_ms?: number;
    };
    VersionResponse: {
      app_name: string;
      changelog?: string;
      display_name: string;
      error?: string;
      stage: string;
      version: string;
    };
  };
}

export interface paths {
  "/": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/chat": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/config": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/create-collection": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/create-collection-cancel/{job_id}": {
    post: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/create-collection-status/{job_id}": {
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/evaluate": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/evaluate-batch": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/evaluate-batch/detect-patterns": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/evaluate-batch/status/{job_id}": {
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/evaluate/": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/sources": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/sources/{source_id}/files": {
    get: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/indexer-tester/sources/{source_id}/files/{filename}": {
    get: {
      parameters: {
        path: {
          source_id: string;
          filename: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/md-pipelines": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/md-pipelines/preview": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/md-pipelines/{name}": {
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/sources": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/sources/{source_id}": {
    get: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    put: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/sources/{source_id}/crawl": {
    post: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/crawler/sources/{source_id}/crawl/status": {
    get: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/sources/{source_id}/pages": {
    get: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/crawler/sources/{source_id}/stats": {
    get: {
      parameters: {
        path: {
          source_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/dashboard-metrics": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/dependencies": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["DependenciesResponse"];
      };
    };
  };
  "/api/webui/dependencies/check-updates": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/dependencies/jobs/{job_id}": {
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["DependencyJobResponse"];
      };
    };
  };
  "/api/webui/dependencies/update": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/dev-console": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/docker/containers": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["DockerListResponse"];
      };
    };
  };
  "/api/webui/docker/containers/start": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/docker/containers/stop": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/docker/events": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/docker/images": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["DockerListResponse"];
      };
    };
  };
  "/api/webui/docker/images/check-update": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/docker/images/pull": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/docker/images/update": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/docker/status": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["DockerStatusResponse"];
      };
    };
  };
  "/api/webui/extensions/disable": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/docker/update": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/enable": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/install": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/installed": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["InstalledExtensionsResponse"];
      };
    };
  };
  "/api/webui/extensions/providers": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/extensions/registry": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["ExtensionRegistryResponse"];
      };
    };
  };
  "/api/webui/extensions/remove": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/tabs": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["ExtensionTabsResponse"];
      };
    };
  };
  "/api/webui/extensions/ui": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/actions/{action_id}": {
    post: {
      parameters: {
        path: {
          extension_id: string;
          action_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/assets/{asset_path}": {
    get: {
      parameters: {
        path: {
          extension_id: string;
          asset_path: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/details": {
    get: {
      parameters: {
        path: {
          extension_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/sandbox/kill": {
    post: {
      parameters: {
        path: {
          extension_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/sandbox/restart": {
    post: {
      parameters: {
        path: {
          extension_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/tab": {
    get: {
      parameters: {
        path: {
          extension_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/extensions/{extension_id}/tab/refresh": {
    post: {
      parameters: {
        path: {
          extension_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/help": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/help/search": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/help/{slug}": {
    get: {
      parameters: {
        path: {
          slug: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/llm-proxy/api-key": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/llm-proxy/api-key/generate": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/llm-proxy/api-key/reveal": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/llm-proxy/builds": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["LlmProxyBuildsGetResponse"];
      };
    };
    put: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["LlmProxyBuildsPutOkResponse"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/llm-proxy/builds/preview-model": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/llm-proxy/builds/{build_id}": {
    get: {
      parameters: {
        path: {
          build_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/llm-proxy/status": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["LlmProxyStatusResponse"];
      };
    };
  };
  "/api/webui/logs": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/model-settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["ModelSettingsGetResponse"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["ModelSettingsPostResponse"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/models": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["ModelsListResponse"];
      };
    };
  };
  "/api/webui/notifications": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/notifications/clear": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/notifications/{nid}/dismiss": {
    patch: {
      parameters: {
        path: {
          nid: number;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/performance/browser-timing": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/performance/startup": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["StartupPerformanceResponse"];
      };
    };
  };
  "/api/webui/pipeline-definition": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/pipeline-preview": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/prompts": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/prompts/trash": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/prompts/trash/{trash_name}": {
    get: {
      parameters: {
        path: {
          trash_name: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    put: {
      parameters: {
        path: {
          trash_name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/prompts/trash/{trash_name}/restore": {
    post: {
      parameters: {
        path: {
          trash_name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/prompts/{name}": {
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    put: {
      parameters: {
        path: {
          name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/providers/catalog": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/proxy-journal": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/proxy-logs": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/proxy-trace/current": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/proxy-traces": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/proxy-traces/clear": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-framework-settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-keyword-collections": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-keyword-collections/{collection_id}": {
    delete: {
      parameters: {
        path: {
          collection_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-model-settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests-v2/run": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests-v2/run/cancel/{job_id}": {
    post: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests-v2/run/status/{job_id}": {
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/filters": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/run": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests/run/cancel/{job_id}": {
    post: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-tests/run/status/{job_id}": {
    get: {
      parameters: {
        path: {
          job_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/runs": {
    delete: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/runs/summary": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/runs/{run_id}": {
    get: {
      parameters: {
        path: {
          run_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/runs/{run_id}/export": {
    get: {
      parameters: {
        path: {
          run_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/rag-tests/{test_id}": {
    delete: {
      parameters: {
        path: {
          test_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
    get: {
      parameters: {
        path: {
          test_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    put: {
      parameters: {
        path: {
          test_id: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-trigger-settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag-trigger-test": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag/collection-settings": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag/collections": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["RagCollectionsResponse"];
      };
    };
  };
  "/api/webui/rag/collections/{collection_name}": {
    delete: {
      parameters: {
        path: {
          collection_name: string;
        };
      };
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag/start": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/rag/status": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["RagStatusResponse"];
      };
    };
  };
  "/api/webui/rag/stop": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/server/stop": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/sessions": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/api/webui/settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["AppSettingsResponse"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["AppSettingsResponse"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/tester-settings": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/tester/chat": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/tester/prompt-preview": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/testing/external-docs/preview": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/api/webui/version": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["VersionResponse"];
      };
    };
  };
  "/health": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/metrics": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/ready": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
  };
  "/v1": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["GenericObject"];
      };
    };
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/v1/chat/completions": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["OpenAiChatCompletionRequest"];
      responses: {
        "200": components["schemas"]["OpenAiChatCompletionResponse"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/v1/external-docs/ingest": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/v1/files/apply-edit": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/v1/messages": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
  "/v1/models": {
    get: {
      parameters: never;
      requestBody: never;
      responses: {
        "200": components["schemas"]["OpenAiModelListResponse"];
      };
    };
  };
  "/v1/models/{model_id}": {
    get: {
      parameters: {
        path: {
          model_id: string;
        };
      };
      requestBody: never;
      responses: {
        "200": components["schemas"]["OpenAiModelResponse"];
      };
    };
  };
  "/v1/responses": {
    post: {
      parameters: never;
      requestBody: components["schemas"]["GenericObject"];
      responses: {
        "200": components["schemas"]["GenericObject"];
        "400": components["schemas"]["ErrorResponse"];
      };
    };
  };
}
