import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.js'],
    include: ['src/**/*.test.{js,jsx,ts,tsx}'],
    coverage: {
      provider: 'v8',
      all: false,
      include: [
        'src/components/ActionableError.jsx',
        'src/components/Card.jsx',
        'src/components/CoreUIBadge.jsx',
        'src/components/CoreUIButton.jsx',
        'src/components/CoreUIConfirmDialog.tsx',
        'src/components/CoreUIModal.jsx',
        'src/components/CoreUINotificationActionButton.jsx',
        'src/components/CoreUIPillTabs.jsx',
        'src/components/CoreUIPipelinePreview.jsx',
        'src/components/CoreUIShowcaseTab.jsx',
        'src/components/CoreUISlider.jsx',
        'src/components/CoreUISubtabs.jsx',
        'src/components/CrawlerTab.jsx',
        'src/components/DevDocumentationTab.jsx',
        'src/components/EmptyState.jsx',
        'src/components/ExtensionRuntimeLoadingView.jsx',
        'src/components/ExtensionRuntimeTab.jsx',
        'src/components/LlmProxyBuildsTab.jsx',
        'src/components/LlmProxyTab.jsx',
        'src/components/ProxyJournalTab.jsx',
        'src/components/ProxyTracesTab.jsx',
        'src/components/RagTestsTab.jsx',
        'src/components/SettingsTab.jsx',
        'src/components/SwaggerTab.jsx',
        'src/components/TestingTab.jsx',
        'src/components/extensionRuntimeTab/buildActionPayload.ts',
        'src/components/extensionRuntimeTab/comparePayload.ts',
        'src/components/extensionRuntimeTab/reportActionOutcome.ts',
        'src/components/extensionRuntimeTab/useExtensionRuntimeTab.ts',
        'src/components/llmProxyBuildsTab/helpers.js',
        'src/components/notificationModuleLabels.js',
        'src/components/ragTab/helpers.js',
        'src/components/ragTestsTab/helpers.js',
        'src/services/i18n.js',
        'src/services/moduleTimings.js',
        'src/utils/elapsedTime.js',
        'src/utils/modelTesterMarkdown.js',
        'src/utils/proxyTraceModel.js',
        'src/utils/proxyTraceWarnings.js',
        'src/utils/userError.js',
      ],
      exclude: [
        'coverage/**',
        'dist/**',
        'scripts/**',
        'src/**/*.test.{js,jsx,ts,tsx}',
        'src/test/**',
      ],
      thresholds: {
        lines: 70,
      },
    },
  },
});
